name: queuemusic
description: Vote for the next song.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.12.0
  firebase_auth: ^3.3.13
  cloud_firestore: ^3.1.8
  sqflite: ^2.0.2
  path_provider: ^2.0.9
  cupertino_icons: ^1.0.4
  provider: ^6.0.2
  uuid: ^3.0.6

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
